### ISSUE TITLE
Bootstrap 5 not implemented?

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/ProjectPortal#2]
Hello Adam,
in some places by the modal, specific to close the modale with "close", and with the "cross", I think the code is not updated with bootstrap 5

`<button type="button" class="close ml-0" data-dismiss="modal">
                        <span>×</span>
                    </button>`

data-dismiss should be **data-bs-dismiss**

in general i think all "data-" should become "data-bs-"
https://getbootstrap.com/docs/5.0/migration/#javascript

best
Thomas

**Comment by aanunez** [comment]
Looks like bootstrap 5 falls back to the bootstrap 4 data annotations correctly without issue. In the current release we support back to redcap 12. In an upcoming release I plan to support redcap 13. The swap to BS5 wasn't until RC 13.4 so I will be leaving this as for now. 

Reminder to self: Fix this when we support only RC 13.4+

**Comment by aanunez** [comment]
I was mistaken in my last comment, bs5 doesn't fall back as expected. I will be releasing a fix. Sorry for not fixing it sooner, I was under the impression that this was a minor issue when it is not.

**Comment by aanunez** [comment]
Resolve in recent commit. Will be including in next release.
